### ISSUE TITLE
clone 下来不能运行啊！

### ISSUE THREAD

**Issue by gitCoy** [qianyinghuanmie/vue2.0-demos#1]
clone 下来不能运行啊

**Comment by qianyinghuanmie** [comment]
不好意思，之前引了v-echarts没有写入到package.json，现在已经修改，你可以再clone一遍试试，记得重新 `npm install`一次

**Comment by qianyinghuanmie** [comment]
@gitCoy 不好意思，之前引了v-echarts没有写入到package.json，现在已经修改，你可以再clone一遍试试，记得重新 npm install一次

**Comment by gitCoy** [comment]
恩啊！我是吧这个文件的引用删除了再运行的！
还有我按照你的方法引用amap总是报错，找不到AMap,哎~

**Comment by qianyinghuanmie** [comment]
@gitCoy  是[调用高德地图](http://www.cnblogs.com/star-wind/p/6774204.html)那一个例子吗？那个，第一要保证先引入高德sdk再去写之后的js，还有注意你的key有没有使用有效的key。

**Comment by qianyinghuanmie** [comment]
@gitCoy  你有没有兴趣一起写这个项目啊，好像你是开始学vue吧，反正就是收集一下常用的demo，像现在只是引入一个高德，其实可以引入百度啊，腾讯啊等等都可以整理出来的，还有其他的功能，类似于常见的文件上传，预览大图等等都可以往上面写。

**Comment by gitCoy** [comment]
可以啊，我是因为公司需要就选择了Vue,感觉网上评论挺好

**Comment by qianyinghuanmie** [comment]
@gitCoy 我邀请你成为协助者了，你需要同意下。我不知道是否要fork才能改代码，你可以试着随便改点什么提交试试。

**Comment by gitCoy** [comment]
好的，用fork应该是避免冲突吧
