### ISSUE TITLE
Uncaught ReferenceError: AMap is not defined

### ISSUE THREAD

**Issue by donaldlulu** [qianyinghuanmie/vue2.0-demos#3]
项目中按步骤抄了高德地图相关代码， 调试出现错误，Uncaught ReferenceError: AMap is not defined， 请问什么原因？

**Comment by qianyinghuanmie** [comment]
@donaldlulu  可能是你所要执行的js在高德地图还没有引入就执行了，能不能看下你network中的加载的顺序，还有就是要配置webpac.base.conf.js文件，加个 ` externals: { 'AMap': 'AMap' }`，你的当前页面的vue代码中要引入  ` import AMap from 'AMap'`

**Comment by RUIYU81** [comment]
我按照上面的步骤  在webpac.base.conf.js文件中加了 externals: { 'AMap': 'AMap' }，在当前页面的vue代码中要引入了 import AMap from 'AMap'，  在mian.js中加载了高德的js文件，但是也会报这个错误

**Comment by qianyinghuanmie** [comment]
`
// 创建高德地图
let createMap = () => {
  const promise = new Promise(function (resolve, reject) {
    let script = document.createElement('script')
    script.type = 'text/javascript'
    script.src = 'https://webapi.amap.com/maps?v=1.3&key=1f648c12a2709a14b0e79551fdc5f791'   // 高德地图
    document.body.appendChild(script)
    if (script.nodeName === 'SCRIPT') {
      resolve()
    } else {
      reject(new Error('Could not script image at ' + script.src))
    }
  })
  return promise
}
createMap().then(function () {
  console.log('读取高德地图成功')
  // 加載當前的ip定位
}).catch(function (error) {
  // 处理 getJSON 和 前一个回调函数运行时发生的错误
  console.log('发生错误！', error)
})`

@LFISH99  这个是原文中的代码，其中的高德的密钥换成自己可以调用的。而且在动态创建生成高德sdk的时候，需要加载其他vue的前面。
也就是说上面的那大段代码保持在下面这段代码的前面就可以了。

`new Vue({
  router,
  render: h => h(App)
}).$mount('#app')`

如果没有用router的话，也是一样的道理，先加载高德sdk，再加载其他vue

**Comment by RUIYU81** [comment]
@qianyinghuanmie 我是按着这个顺序写的（但是我把高德地图抽成一个单独的js了）。但是很奇怪，如果在别的vue中没有import AMap from 'AMap'，从network中可以看到有加载了高德的sdk，反之就会报Uncaught ReferenceError: AMap is not defined。从network中就只加载了html和app.js而已
这个我main.js的代码：
// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue'
import App from './App'
import router from './router'
import { AMap } from './utils/map'

Vue.config.productionTip = false

// 加载高德地图
AMap().then(() => {
    console.log('读取高德地图成功');
}).catch((error) => {
    console.log('发生错误！', error);
})

new Vue({
     router,
     render: h => h(App)
}).$mount('#app')

**Comment by qianyinghuanmie** [comment]
@LFISH99  有一个方法可以测试，之前我也是这样测试，我在加载高德地图的时候调试了个`console.log('读取高德地图成功');` 你可以在需要使用的vue中先不要`import AMap from 'AMap'`（按照你说的是可以加载出来的），然后比对下，高德地图sdk和要使用vue的加载的先后顺序。如果vue先加载的话，就会出现`AMap is not defined`

**Comment by RUIYU81** [comment]
vue先加载了，怎样才能让它后加载呢？

**Comment by RUIYU81** [comment]
在webpack.base.conf.js我把
externals: {
    'AMap': 'AMap'
  }改成
externals: {
    'AMap': 'window.AMap'
  }

不报 AMap is not defined， 改报undefined了
但是从后台看sdk却加载出来了

**Comment by qianyinghuanmie** [comment]
@LFISH99 如果你实在还是不行的话，也可以直接把sdk引入放在index.html里面 的上方
![image](https://user-images.githubusercontent.com/19732025/33139146-613a43e4-cfe7-11e7-99b6-4e52d01a973f.png)
这样的话，就可以直接在你的vue页面上`import AMap from 'AMap'`

**Comment by LiSiris** [comment]
你解决这个问题了吗?我现在问题和你一样

**Comment by tongjh2** [comment]
你的例子： https://qianyinghuanmie.github.io/#/map 直接打开这个页的话报错 

console中的错误信息
读取高德地图成功
ReferenceError: AMap is not defined

**Comment by tongjh2** [comment]
我加了一个setTimeout就可以了，看来是加载顺序的问题

main.js

import VueAMap from 'vue-amap';
VueAMap.initAMapApiLoader({
    key: '申请的高德key',
    plugin: ['AMap.PlaceSearch', 'AMap.Geolocation', 'AMap.AMapManager', 'AMap.Geocoder']
});
Vue.use(VueAMap);

组件中的方法使用

// 根据地址获取经纬度
// 根据地址获取经纬度
getCenter(address) { 
    var _this = this
    setTimeout(()=>{
        AMap.service(["AMap.Geocoder"], function() {                
            var geocoder = new AMap.Geocoder({radius:1000});
            geocoder.getLocation(address,function(status, result) {
                if (status === 'complete' && result.info === 'OK') {
                    var geocodes = result.geocodes;
                    if(geocodes && geocodes.length>0){
                        let geocode = geocodes[0];
                        _this.center = [geocode.location.lng,geocode.location.lat];
                        _this.currentWindow.position = _this.center;
                    }
                }
            });
        });
    });            
},

**Comment by wangjiawu** [comment]
在mapvue中怎么引入高德地图，是通过下载高德地图的sdk？还是npm下载AMap？

**Comment by acongy** [comment]
有同志搞定了？？？

**Comment by acongy** [comment]
> 在mapvue中怎么引入高德地图，是通过下载高德地图的sdk？还是npm下载AMap？

两年了，你是怎么解决？？？
